### ISSUE TITLE
About Repeat Computing

### ISSUE THREAD

**Issue by SongJgit** [anubhabghosh/danse_jrnl#3]
Hello, I'm back to asking questions.
I found some problems while adapting for my project.
It's about double computing, like the following code.
https://github.com/anubhabghosh/danse_jrnl/blob/43888dd8040fb65c67406e4a58a2b9674b148f1c/src/danse_supervised.py#L89-L94
https://github.com/anubhabghosh/danse_jrnl/blob/43888dd8040fb65c67406e4a58a2b9674b148f1c/src/danse.py#L89-L97
These two codes are supervised and unsupervised respectively.
`self.H @ self.L_xt_yt_prev @ torch.transpose(self.H, 0, 1) + self.C_w` has been computed twice.

I found that  when I try to speed things up and use one calculation instead, like the following
```python
L_yt_current = self.H @ self.L_xt_yt_prev @ torch.transpose(self.H, 0, 1) + self.C_w
Re_t_inv = torch.inverse(L_yt_current)
self.K_t = (self.L_xt_yt_prev @ (self.H.T @ Re_t_inv))
self.mu_xt_yt_current = self.mu_xt_yt_prev + torch.einsum('ntij,ntj->nti',self.K_t,(Yi_batch - torch.einsum('ij,ntj->nti',self.H,self.mu_xt_yt_prev)))
self.L_xt_yt_current = self.L_xt_yt_prev - (torch.einsum('ntij,ntjk->ntik',
                    self.K_t, L_yt_current) @ torch.transpose(self.K_t, 2, 3))
```

This has some performance differences compared to the original implementation. 
Like the following figure, green is the original implement, and red is my modified like above, in the same seed.
![image](https://github.com/anubhabghosh/danse_jrnl/assets/30189040/c7ce5141-4926-4f8e-be8e-488523e55b2b)

Is there any particular reason for this double computing?
Like gradients, or whatever?

**Comment by anubhabghosh** [comment]
No particular reason I guess, the optimized version that you proposed looks also okay.
