### ISSUE TITLE
Some issues about reproducing the training process

### ISSUE THREAD

**Issue by yuxuanfanOrion** [anubhabghosh/danse_jrnl#6]
Hi, thanks for your great work

When I try to reproduce the training process refering to the README.md file, I met some issues

When I try Run the training for DANSE by calling main_danse_opt.py

(base) yfan546@7dd886f7a9a7:~/workplace/tbsi/danse_jrnl$ python3 main_danse_opt.py --mode train --rnn_model_type gru --dataset_type LorenzSSM --datafile ./data/synthetic_data/trajectories_m_3_n_3_LorenzSSM_data_N_1000_T_100_sigmae2_-10.0dB_smnr_0.0dB.pkl --splits ./data/synthetic_data/splits_m_3_n_3_LorenzSSM_data_N_1000_T_100_sigmae2_-10.0dB_smnr_0.0dB.pkl
datafile: ./data/synthetic_data/trajectories_m_3_n_3_LorenzSSM_data_N_1000_T_100_sigmae2_-10.0dB_smnr_0.0dB.pkl
trajectories_m_3_n_3_LorenzSSM_data_N_1000_T_100_sigmae2_-10.0dB_smnr_0.0dB.pkl
Traceback (most recent call last):
  File "main_danse_opt.py", line 210, in <module>
    main()
  File "main_danse_opt.py", line 57, in main
    _, n_states, n_obs, _, T, N_samples, sigma_e2_dB, smnr_dB = parse("{}_m_{:d}_n_{:d}_{}_data_T_{:d}_N_{:d}_sigmae2_{:f}dB_smnr_{:f}dB.pkl", datafile.split('/')[-1])
TypeError: cannot unpack non-iterable NoneType object

I have met this error, is there something wrong when I follow your README? I already generated the data

**Comment by anubhabghosh** [comment]
Hi, thanks for bringing the issue to my notice. I just noticed that there is a slight error in the filename format in the README.md file. 

The data generation script generates a file name typically of the format: 
```
trajectories_m_3_n_3_LorenzSSM_data_T_100_N_1000_sigmae2_-10.0dB_smnr_0.0dB.pkl 
```
And in the README.md instruction it was mentioned with the positions of `T` and `N` reversed. So, the correct format of running should be 
```
python3 main_danse_opt.py \
--mode train \
--rnn_model_type gru \
--dataset_type LorenzSSM \
--datafile ./data/synthetic_data/trajectories_m_3_n_3_LorenzSSM_data_T_100_N_1000_sigmae2_-10.0dB_smnr_0.0dB.pkl \
--splits ./data/synthetic_data/splits_m_3_n_3_LorenzSSM_data_T_100_N_1000_sigmae2_-10.0dB_smnr_0.0dB.pkl
```

I will make a fix in the README file about this and update here. Hope the confusion is resolved now!

**Comment by yuxuanfanOrion** [comment]
> Hi, thanks for bringing the issue to my notice. I just noticed that there is a slight error in the filename format in the README.md file.您好，感谢您将这个问题通知给我。我刚刚注意到在 README.md 文件中，文件名格式有一点小错误。
> 
> The data generation script generates a file name typically of the format:数据生成脚本生成的文件名通常格式如下：
> 
> ```
> trajectories_m_3_n_3_LorenzSSM_data_T_100_N_1000_sigmae2_-10.0dB_smnr_0.0dB.pkl 
> ```
> 
> And in the README.md instruction it was mentioned with the positions of `T` and `N` reversed. So, the correct format of running should be在 README.md 的说明中提到， `T` 和 `N` 的位置被颠倒了。因此，正确的运行格式应该是：
> 
> ```
> python3 main_danse_opt.py \
> --mode train \
> --rnn_model_type gru \
> --dataset_type LorenzSSM \
> --datafile ./data/synthetic_data/trajectories_m_3_n_3_LorenzSSM_data_T_100_N_1000_sigmae2_-10.0dB_smnr_0.0dB.pkl \
> --splits ./data/synthetic_data/splits_m_3_n_3_LorenzSSM_data_T_100_N_1000_sigmae2_-10.0dB_smnr_0.0dB.pkl
> ```
> 
> I will make a fix in the README file about this and update here. Hope the confusion is resolved now!我将在 README 文件中对此进行修复，并在这里更新。希望这次的困惑已经解决了！

Thank you very much for your reply, I'll try it and close the issue!

**Comment by anubhabghosh** [comment]
Sure, I'll also update the repo in the mean time with some changes, so will make a comment here soon!
